version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1/
    depends_on:
      - backend
    networks:
      - rag-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/voiceai
      - ollama_url=http://ollama:11434
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - rag-network

  db:
    build: ./backend/app/db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=voiceai
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-network

volumes:
  postgres_data:
  ollama_data:

networks:
  rag-network:
    driver: bridge